[phases.setup]
nixPkgs = ['gradle', 'jdk21']

[phases.build]
cmds = [
  'chmod +x gradlew',
  './gradlew clean build -x test',
  'ls -la build/libs/'
]

[start]
cmd = 'java -jar build/libs/green-day-bank-api-1.0.0.jar'
